"shutdown_actions": suppress "missing initializer" warnings/errors
gcc reports:

> gui.c:1795:3: error: missing initializer for field ‘padding’ of
> ‘GActionEntry’ {aka ‘const struct _GActionEntry’}
> [-Werror=missing-field-initializers]
>  1795 |   { "shutdown", activate_action, NULL, NULL, NULL },
>
> gui.c:1796:3: error: missing initializer for field ‘padding’ of
> ‘GActionEntry’ {aka ‘const struct _GActionEntry’}
> [-Werror=missing-field-initializers]
>  1796 |   { "reboot", activate_action, NULL, NULL, NULL },

I've found this only now because:

- this is the first time I'm building virt-p2v with GTK3,

- the "shutdown_actions" array depends on USE_POPOVERS which depends on
  GTK3 being selected,

- the "missing-field-initializers" warning (treated as an error) has
  recently been enabled via "-Wextra" in commit 391f9833d398 ("p2v-c.m4:
  elicit a stricter set of warnings from gcc", 2022-09-23).

Use designated initializers; with those, "-Wmissing-field-initializers"
does not complain about the "padding" field.

Signed-off-by: Laszlo Ersek <lersek@redhat.com>
Message-Id: <20220926081812.12585-2-lersek@redhat.com>
[lersek@redhat.com: rewrite with designated initializers, at Daniel's
 suggestion]
Suggested-by: Daniel P. Berrangé <berrange@redhat.com>
Acked-by: Richard W.M. Jones <rjones@redhat.com>